-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
-- DEFAULT. DO NOT EDIT. THESE VALUES ARE LOADED FROM data/dayz/config.txt EDIT THAT FILE INSTEAD OR DIE.
PHDayZ = PHDayZ or {}

PHDayZ.version = 6.66 -- If this value is newer than your config.txt value, then it will update for you. This is for that reason.

PHDayZ.scoreboardtitle = "[ALL] Oryum | Simple DayZ"
PHDayZ.scoreboardhostname = true -- Override hostname with scoreboard title?
PHDayZ.ScoreboardShowSupporters = true -- Show people who are supporters on gmoddayz.net with a flashy title on your scoreboard? :DD
PHDayZ.GuideURL = "" -- Le wiki pour le gamemode
PHDayZ.VIPURL = "" -- set this to a string, like above for your vip shop

PHDayZ.RagdollDeaths = true -- Are ragdolls used instead of graves? This can cause crashes.
PHDayZ.UseCheatBanlist = true -- Turn this on if you want to stop previously banned cheaters (100% proof) playing on your server

PHDayZ.AdminModeTimer = 3 -- The amount of time it takes admins to turn into admin mode via noclip?
PHDayZ.AdminsHide = false -- Are admins hidden in the scoreboard / chatbox (Scorpy's Simple Chatbox only!)
PHDayZ.AdminsCanUseSpawnMenu = true -- Can admins abuse their powers and spawn guns/entities from the Q menu?
PHDayZ.DisableStartupInfo = false -- Disable gamemode loading information, in case everything is working and you prefer a clean console like me.

PHDayZ.BlockedEntities = {"func_lod"} -- Prevents interacting with these entities, at all. Useful if certain maps have prop buildings.

PHDayZ.ServerLanguage = "english" -- This MUST be set to a filename inside language/lang/ folder! If your language doesn't exist, copy the english one and change it's name/contents!
PHDayZ.Skybox_ForcePainted = false -- Does the server force the skybox to be painted by Sky Editor?

PHDayZ.ThirdPerson = true -- Can Players press F2 to enter third person? (may be removed in future)
PHDayZ.AFKSystem = true -- Does the gamemode mark people as afk if they haven't done anything in a while?
PHDayZ.AFKTimer = 300 -- How long does a player do nothing before they are marked as afk? (In seconds)
PHDayZ.MaxChatDistance = 15 -- Local chat distance IN METERS
PHDayZ.MaxRadzoneParticles = 100 -- Max particles spawned for radiation zones.
PHDayZ.AllowPropSpawn = false -- If this is true, you'll need prop protection as EVERYONE is given a physgun by default. Be careful!
PHDayZ.PropCostMultiplier = 2 -- This multiplies the mass of the prop by this number to generate the cost.
PHDayZ.PropHealthMultiplier = 15 -- The math to multiply props health by. Generated by the size of the prop.
PHDayZ.AllowPropDamage = true -- If this is enabled, player owned props can be damaged and destroyed. Also enables clientside GUI.
PHDayZ.MaxPropSize = 2000 -- I wouldn't suggest setting this higher or people will fuck you with massive props.
PHDayZ.AllowShareItemModel = false -- Enabling this allows players to spawn props that have the same model's as loot on the server.
PHDayZ.PropRemoveTimer = 120 -- Setting this to 0 will never remove props, above this time it will remove a players props when they disconnect after X seconds (Without reconnecting).

PHDayZ.NPC_PlayerDamageScale = 0.6 -- The damage scaled (from 1) when an npc hurts a player.
PHDayZ.NPCS_AnimalsEnabled = false -- Enabling this turns on animal support. They spawn on zombie spawn points.
PHDayZ.NPCS_EnemiesEnabled = false -- Enabling this turns on vj insurgent (enemies with guns) support. They also spawn on zombie spawn points.

PHDayZ.Player_MaxWeight = 100 -- The maximum weight the inventory can hold without additionals or perks.
PHDayZ.VehicleMaxHealth = 250 -- The maximum health of any vehicle spawned by the gamemode.
PHDayZ.HelicopterEnt = "sent_sakariashelicopter" -- The helicopter entity spawned by the gamemode.

PHDayZ.Player_DeathBlackScreen = true -- If this is enabled, player's screen fades to black when they die.
PHDayZ.Player_FirstPersonDeath = true -- If this is enabled, players see through their own eyes when they die.

PHDayZ.CarePackage_Timer = 1800 -- This is 1 hour. This dictates the time they spawn.
PHDayZ.CarePackage_MaxItems = 20 -- The maximum items allowed inside the crate.
PHDayZ.CarePackage_MaximumQuantity = 8 -- The maximum amount of one item.
PHDayZ.CarePackage_PlayerLimit = 10

PHDayZ.LootableRespawnTimer = 900 -- In seconds, how long does it take for lootable entities to respawn their goodies?
PHDayZ.LootableItemSetup = {} -- If you want extra models to be supported (and show certain things other than random) add them to this table
PHDayZ.LootableItemSetup["default"] = {"Food", "Drinks", "Medical", "Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources"}
PHDayZ.LootableItemSetup["models/items/ammocrate_ar2.mdl"] = {"Primaries", "Secondaries", "Ammo"}
PHDayZ.LootableItemSetup["models/props/cs_militia/gun_cabinet.mdl"] = {"Primaries", "Secondaries", "Ammo"}
PHDayZ.LootableItemSetup["models/props_c17/furniturefridge001a.mdl"] = {"Food", "Drinks"}
PHDayZ.LootableItemSetup["models/props_junk/wood_crate001a_damaged.mdl"] = {"Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources"}
PHDayZ.LootableItemSetup["models/props_c17/oildrum001.mdl"] = {"Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources"}
PHDayZ.LootableItemSetup["models/props_c17/furnituredresser001a.mdl"] = {"Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources"}
PHDayZ.LootableItemSetup["models/props_interiors/furniture_desk01a.mdl"] = {"Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources"}
PHDayZ.LootableItemSetup["models/props_junk/trashdumpster01a.mdl"] = {"Clothes", "Pants", "Shoes", "Misc", "Parts", "Tools", "Resources", "Food", "Drinks", "Medical"}
PHDayZ.LootableItemSetup["models/props/cs_militia/footlocker01_closed.mdl"] = {"Clothes", "Pants", "Shoes"}
PHDayZ.LootableItemSetup["models/props_c17/furniturecupboard001a.mdl"] = {"Medical"}
PHDayZ.LootableItemSetup["models/props_lab/partsbin01.mdl"] = {"Parts", "Tools", "Resources", "Misc", "Medical"}
PHDayZ.LootableItemSetup["models/dayz/misc/dayz_campfire.mdl"] = {"Food", "Drinks", "Medical", "Misc", "Tools", "Resources"}

PHDayZ.ModelToNiceName = {} -- The name of the entity when you look at it. This way beats networking!
PHDayZ.ModelToNiceName["models/items/ammocrate_ar2.mdl"] = "Ammo Crate"
PHDayZ.ModelToNiceName["models/props/cs_militia/gun_cabinet.mdl"] = "Gun Cabinet"
PHDayZ.ModelToNiceName["models/props_c17/furniturefridge001a.mdl"] = "Fridge"
PHDayZ.ModelToNiceName["models/props_c17/furnituredrawer001a.mdl"] = "Drawer"
PHDayZ.ModelToNiceName["models/props_junk/wood_crate001a_damaged.mdl"] = "Wooden Crate"
PHDayZ.ModelToNiceName["models/props_c17/oildrum001.mdl"] = "Oil Drum"
PHDayZ.ModelToNiceName["models/props_c17/furnituredresser001a.mdl"] = "Dresser"
PHDayZ.ModelToNiceName["models/props_junk/trashdumpster01a.mdl"] = "Trash Dumpster"
PHDayZ.ModelToNiceName["models/props/cs_militia/footlocker01_closed.mdl"] = "Foot Locker"
PHDayZ.ModelToNiceName["models/props_c17/furniturecupboard001a.mdl"] = "Cupboard"
PHDayZ.ModelToNiceName["models/props_lab/partsbin01.mdl"] = "Bullshit"
PHDayZ.ModelToNiceName["models/dayz/misc/dayz_campfire.mdl"] = "Camp Fire"
PHDayZ.ModelToNiceName["models/props_c17/display_cooler01a.mdl"] = "Cooler"

PHDayZ.Skills_XPPerSkillPoint = 150 -- This is 1 hour. This dictates the time they spawn.
PHDayZ.Skills_LoseOnDeath = true -- Do you lose a random amount of skill points on death?
PHDayZ.Skills_MaximumLoss = 2 -- The maximum amount of skill points to lose at one time.
PHDayZ.Skills_MinimumLoss = 0 -- The minimum ^ 

PHDayZ.ItemPerishTime = 300 -- The time it takes for spawned loot, or dropped items to despawn after created.
PHDayZ.GravePerishTime = 300 -- The time it takes for graves to despawn after created.
PHDayZ.BackpackPerishTime = 300 -- The time it takes for backpacks to despawn after created.

PHDayZ.MenuCamPos = Vector(-2551.949951, -9562.596680, 294.795013) -- The position of the camera that players will see when on the main menu.
PHDayZ.MenuCamAngles = Angle(18.370, -52.120, 0.000) -- The angles of the camera that players will see when on the main menu.
PHDayZ.ShowGSAdvert = false -- If you want to advertise my company, turn this on!
PHDayZ.ShowVIPColors = true -- This turns the blue coloring on and off for names.

PHDayZ.FireSpread = false -- Turning this on, makes fire spread over time.
PHDayZ.WeaponCooldownFreshSpawns = true -- Turning this on stops fresh spawners from using weapons for X amount of time.
PHDayZ.Player_FreshSpawnTime = 60 -- This is the amount of time you're classed as a freshspawn for. Set this in seconds.
PHDayZ.Player_FistsEnabled = true -- Do players spawn with fists?
PHDayZ.Player_PickupObjectsWithAlt = true -- Can Players pickup items with the ALT(+walk) key?

PHDayZ.WeaponRarityDamagePercent = 8 -- The percentage weapons damage is increased by based on the rarity.

PHDayZ.InstantProcesses = false -- If this is enabled, all items that normally take time to use, are now used instantly.

PHDayZ.Player_XPPerMin = 5 -- How much XP does a player get for just playing per minute? Keep this low or it will break your economy.
PHDayZ.Player_XPLevelMultiplier = 500 -- This gets multiplied by the players level. 500 for level 1, 1000 for level 2, 1500 for level 3, etc.
PHDayZ.Player_LooseXPDeath = true -- True/False to enable or disable losing experience on death.
PHDayZ.Player_XPLossPercentage = 25 -- If the above is true, out of 100, what's the loss percentage?
PHDayZ.Player_XPLossCap = 100 -- If set to more than 0, the XP taken from players will never be more than this when they die.
PHDayZ.Player_XPAwardOnZombieKill = 25 -- How much XP you get on killing a Zombie.
PHDayZ.GroupXPBonusPerc = 20 -- How much XP do your group members share to each other?

PHDayZ.hungermaterial = "gui/icon_cyb_64_hunger.png"
PHDayZ.thirstmaterial = "gui/icon_cyb_64_thirst.png"

PHDayZ.DebugMode = false -- Turn this on to see prints about loot being spawned in console.
PHDayZ.LogTypes = { 1, 2, 3, 4, 5 } -- I'd leave this as is, however: 1=shop,2=admin,3=loot,4=death,5=exploit

PHDayZ.TotalAllowedCars = 4 -- The maximum amount of JEEPS allowed on the server.

PHDayZ.AmmoSpawnRate = 10 -- Percentage. Of all spawns, how many are theoretically spawned as ammo?
PHDayZ.LootTimer = 2 -- The seconds between a new set of loot being randomly spawned.
PHDayZ.TotalAllowedLoot = 300 -- The maximum amount of loot spawned at any time on the server.
PHDayZ.LootSpawnAmount = 2 -- The amount of loot that spawns (of each type) per batch.

PHDayZ.ZombieSpawnNearPlayers = false -- Force spawn zombies near players? This is hardcoded at 20 second intervals to prevent the same player from being spammed.
PHDayZ.ZombiePerPlayerTimer = 20 -- The ABSOLUTE fastest time zombies can be spawned near the same player.
PHDayZ.ZombieTimer = 2 -- The seconds between a new zombie being spawned randomly.
PHDayZ.TotalAllowedZombies = 100 -- The maximum amount of zombies spawned at any time on the server.
PHDayZ.ZombieSpawnCheckNear = true -- Do zombies check if there is a nearby zombie before they spawn?
PHDayZ.ZombieItems = { -- What do zombies have a chance of dropping on death?
	"item_medic1",
	"item_medic2",
	"item_apple",
	"item_food1",
	"item_fabric",
	"item_egg",
	"item_potato",
	"item_drink1",
	"item_drink2",
	"item_drink3",
	"item_shoe",
	"item_hula",
	"item_knife",
	"item_ammo_ragingbull",
	"item_ammo_m3super90",
	"item_ammo_glock18",
	"item_ammo_g3sg1",
	"item_ammo_fiveseven",
	"item_ammo_famas",
	"item_ammo_deagle",
	"item_ammo_ak47",
	"item_ammo_357sig"
}

PHDayZ.VJBaseSupport = true -- Enable for override with VJBase zombies: 131759821, 152529683
PHDayZ.ZombieTypes = {} -- What zombies are available for spawning? All spawned entities here will have ENTITY.IsZombie set to true on them.
PHDayZ.ZombieTypes["npc_nb_common"] = 100 -- Zombie class name and rarity. Spawns a zombie with the highest (closest to 0) rarity based  -- How much chance of zombies dropping money?
PHDayZ.ZombieMeatChance = 25 -- How much chance of zombies dropping meat?
PHDayZ.ZombieItemChance = 15 -- How much chance of zombies dropping an item from the table above?

PHDayZ.Player_DefaultWalkSpeed = 200 -- Normal speed
PHDayZ.Player_DefaultJumpPower = 250 -- How high a player jumps
PHDayZ.Player_DefaultRunSpeed = 250 -- How fast they run while consuming stamima.
	
PHDayZ.Player_HungerTimer = 14 -- The seconds between one unit of hunger being deducted.
PHDayZ.Player_ThirstTimer = 12 -- The seconds between one unit of thirst being deducted.
PHDayZ.Safezone_NoDrain = true -- Does Hunger/Thirst decrease in the safezone areas?
PHDayZ.Safezone_NoRegen = false -- Do blood, health and other stats regen in the safezone?

PHDayZ.Player_HungerThirstSounds = true -- Do players make noises when dieing of hunger or thirst?
PHDayZ.Player_StarvedHit = 1 -- The amount of health that is deducted each time a player is starving.
PHDayZ.Player_ParchedHit = 2 -- The amount of health that is deducted each time a player is parched.

PHDayZ.ShopSellPercentage = 20 -- The percentage players get when they sell an item.
PHDayZ.ShopSellPercentageVIP = 35 -- The percentage players get (on top) when they sell an item at the vip shop.
PHDayZ.ShopAlwaysSellCredits = false -- Does the shop have an infinite supply of credits? (Once sold)

PHDayZ.ShopMaxItems = 30 -- The Maximum items that are sold in the shop at any one time.
PHDayZ.ShopMinItems = 5 -- The Minimum items that are sold in the shop at any one time.
PHDayZ.ShopMaxStock = 0 -- The maximum amount of one item allowed to be sold to the shop. Set to 0 to disable limits.
PHDayZ.ShopAllowSoldOutStock = true -- False to disable the shop dealer being allowed to sell stock that doesn't exist (i.e. instantly sold out stock for realism.)
PHDayZ.ShopAdjustPriceToStock = true -- The more of this item he has, the less he will pay for it and vice versa.
PHDayZ.ShopBuyEnabled = true -- Can people purchase from the shop? This disables the relevant shop tab and all purchase functionality.
PHDayZ.ShopSellAll = true -- Does the shop override all the above options and sell all items that were sold to it?
PHDayZ.Player_NamedDistance = 500 -- The distance you can see player names from.

PHDayZ.Player_SpawnItems = { -- The items players will spawn with by default. Remember this IS exploitable as they WILL drop these items on death.
	{ item = "item_drink1", amt = 1 },
	{ item = "item_crumpet", amt = 1 },
	{ item = "item_medic1", amt = 1 }
}

PHDayZ.MakeNPCEnabled = true -- Can Admins (Not SuperAdmins!) use dz_makenpc

PHDayZ.VIPGroups = { "vip", "superadmin" } -- The groups that are recognised as VIP. Lowercase names only!
PHDayZ.VIPHasAllPerks = false -- does the vip group have all perks by default?

PHDayZ.TipIcons = {} -- The Tip system that appears in the bottom right, 4 different types. Change these icons how you see fit. Automatically resourced.
PHDayZ.TipIcons[1] = "cyb_mat/cyb_blank.png"
PHDayZ.TipIcons[2] = "cyb_mat/cyb_blank.png"
PHDayZ.TipIcons[3] = "cyb_mat/cyb_blank.png"
PHDayZ.TipIcons[4] = "cyb_mat/cyb_blank.png"

PHDayZ.Player_BountyKillsReq = 10 -- The amount of kills that are required to become a Bounty (Hunted).
PHDayZ.Player_BanditKillsReq = 4 -- The amount of kills that are required to become a Bandit.

PHDayZ.InitialSpawnPoints = {} -- Where players spawn while they are choosing a character (Make this a safe area!) dz_setinitialspawn
PHDayZ.SafeZoneTeleportEnabled = true -- can players teleport to and from the safezone with !sz
PHDayZ.SafeZoneSpawnEnabled = true -- do players always spawn in the safezone?
PHDayZ.SafeZoneTeleportPoses = {} -- Where people teleport when they try to use !sz. dz_setszteleportpos
PHDayZ.SafeZoneForceInitial = false -- Force all players to spawn in safezone regardless of disconnect position?
PHDayZ.SafeZoneTeleportChat = false -- Allow people to use !sz to teleport instead of entities. (dz_makeinteractable 3)
PHDayZ.SafeZoneArenaPos = {} -- Where is the arena position? dz_setarenapos

PHDayZ.Player_DeathTime = 15 -- The amount of seconds wait until respawn is available (after death).
PHDayZ.Player_VIPDeathTime = 6 -- Same as above, except VIP wait time.

PHDayZ.Player_TagTime = 60 -- The amount of time the player is blocked from accessing the safezone (and being protected) after attacking or being attacked.
PHDayZ.Player_VIPTagTime = 35 -- Same as above, except for VIP.

PHDayZ.DefaultBankWeight = 1500
PHDayZ.BankMaxWeight = {} -- Exactly what it says on the tin. The maximum weight the respective groups have in their bank.
PHDayZ.BankMaxWeight[ "guest" ] = 1500
PHDayZ.BankMaxWeight[ "user" ] = 1500
PHDayZ.BankMaxWeight[ "member" ]	= 1500
PHDayZ.BankMaxWeight[ "vip" ] = 4000
PHDayZ.BankMaxWeight[ "vipadmin" ] = 4000
PHDayZ.BankMaxWeight[ "admin" ] = 4000
PHDayZ.BankMaxWeight[ "superadmin" ] = 4000
PHDayZ.BankMaxWeight[ "owner" ] = 4000
PHDayZ.BankMaxWeight[ "founder" ] = 4000

PHDayZ.ServerTickerEnabled = false -- Is the server ticker enabled?
PHDayZ.ServerTickerColor = Color(0, 0, 0, 200)
PHDayZ.ServerTickerTextColor = "255,255,102"
PHDayZ.ServerTickerDelay = 120
PHDayZ.ServerTickerPixelDepth = 40
PHDayZ.ServerTickerWidthPerc = 0.4 -- Percentage as a float 0-1
PHDayZ.ServerTicker = {
	"The server is running GModDayZ v" .. PHDayZ.version,
	"Content errors? Visit http://gmoddayz.net/resources/",
	"Global Chat? Write // <message> in chat!",
	"Don't know how to open the Menus? Press F4.",
	"Check our sites for updates at https://alama.eu/triaxe/shop/"
}