ITEM = {}
ITEM.Name = ".338 Lapua"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ".338 Lapua rounds."
ITEM.Model = "models/Items/BoxSRounds.mdl"
ITEM.Color = Color(150, 150, 150, 255)
ITEM.Weight = 0
ITEM.SpawnChance = 15	
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.LootType = { "Weapon" }
ITEM.ClipSize = 5
ITEM.AmmoType = ".338 Lapua"
ITEM.TimeToProcess = 1
ITEM.NoBlueprint = true
ITEM.ReqCraft = { "item_bulletcasing", "item_gunpowder_proc", "item_gunpowder_proc" }
ITEM.Rarity = 1