ITEM = {}
ITEM.Name = "9x19mm"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "9x19mm Rounds."
ITEM.Model = "models/Items/BoxMRounds.mdl"
ITEM.Color = Color(127, 127, 255, 255)
ITEM.Weight = 0
ITEM.SpawnChance = 25
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.LootType = { "Weapon" }
ITEM.ClipSize = 20
ITEM.AmmoType = "9x19MM"
ITEM.NoBlueprint = true
ITEM.TimeToProcess = 1
ITEM.ReqCraft = { "item_bulletcasing2", "item_gunpowder", "item_gunpowder" }
ITEM.Rarity = 1