ITEM = {}
ITEM.Name = "5.56x45mm"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "5.56x45mm rounds."
ITEM.Model = "models/Items/BoxSRounds.mdl"
ITEM.Color = Color(255, 255, 0, 255)
ITEM.Weight = 0
ITEM.SpawnChance = 30
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.LootType = { "Weapon" }
ITEM.ClipSize = 25
ITEM.AmmoType = "5.56x45MM"
ITEM.NoBlueprint = true
ITEM.TimeToProcess = 1
ITEM.ReqCraft = { "item_bulletcasing", "item_gunpowder", "item_gunpowder", "item_gunpowder" }
ITEM.Rarity = 1