ITEM = {}
ITEM.Name = "7.62x39mm"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "7.62x39mm FMJ Rounds."
ITEM.Model = "models/Items/BoxSRounds.mdl"
ITEM.Weight = 0
ITEM.SpawnChance = 30
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.LootType = { "Weapon" }
ITEM.ClipSize = 30
ITEM.AmmoType = "7.62x39MM"
ITEM.NoBlueprint = true
ITEM.TimeToProcess = 1
ITEM.ReqCraft = { "item_bulletcasing", "item_gunpowder", "item_gunpowder", "item_gunpowder" }
ITEM.Rarity = 1