ITEM = {}
ITEM.Name = "Grenade"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Throw to inflict pain."
ITEM.Model = "models/weapons/w_eq_fraggrenade_thrown.mdl"
ITEM.Weight = 5
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.ClipSize = 1
ITEM.AmmoType = "Frag Grenades"
ITEM.Gun = true
ITEM.Tertiary = true
ITEM.LevelReq = 6
ITEM.ReqCraft = { "item_fuse", "item_gunpowder_ref", "item_soddenrag", "item_emptycan" }
ITEM.Weapon = "cw_frag_grenade"
ITEM.Rarity = 4