ITEM = {}
ITEM.Name = "Metal Scraps"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Raw twisted and misshapen metal.\nCan be turned into many things."
ITEM.Model = "models/gibs/scanner_gib02.mdl"
ITEM.Weight = 0.1
ITEM.NoBlueprint = true
ITEM.CantDecompile = true
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.GivePer = 2
ITEM.DontStock = true
ITEM.ReqCraft = { "item_ironore" }