ITEM = {}
ITEM.Name = "Bullet Casing (9mm)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Bullet casings... what else?"
ITEM.Model = "models/weapons/shell.mdl"
ITEM.Weight = 0
ITEM.Price = 10	
ITEM.SellPrice = 8	
ITEM.SpawnChance = -1
ITEM.CantDecompile = true
ITEM.NoBlueprint = true
ITEM.OverrideCamPos = Vector(4, 4, 4)
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.GivePer = 3
ITEM.TimeToProcess = 3
ITEM.ReqCraft = {"item_metal"}
ITEM.UsedInCrafting = true