ITEM = {}
ITEM.Name = "Sand"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Do you wanna build a snowma-... sandcastle?"
ITEM.Model = "models/props_junk/garbage_bag001a.mdl"
ITEM.Material = "models/props_c17/FurnitureMetal001a"
ITEM.Color = Color(255,230,135)
ITEM.Weight = 0.1
ITEM.Price = 20	
ITEM.NoBlueprint = true
ITEM.SpawnChance = -1
ITEM.CantDecompile = true
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.ReqCraft = { "item_stone" } 