ITEM = {}
ITEM.Name = "Fabric"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Torn up clothes. Stops Bleeding when used."
ITEM.Model = "models/dayz/misc/dayz_fabric1.mdl"
ITEM.Weight = 1
ITEM.SpawnChance = 35
ITEM.SpawnOffset = Vector(0,0,0)
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.CanIgnite = true
ITEM.LootType = { "Industrial" }
ITEM.ReqCraft = { "item_shoe", "item_shoe" }
ITEM.CantDecompile = true
ITEM.TimeToProcess = 2
ITEM.UseSound = "items/medshot4.wav"
ITEM.UseEndSound = "heal.wav"
ITEM.ProcessFunction = function(ply, item) ply:SetBleed(false) end
ITEM.NoBlueprint = true