ITEM = {}
ITEM.Name = "Plastic"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Plastic. Multiple uses."
ITEM.Model = "models/props_junk/rock001a.mdl"
ITEM.Material = "models/player/shared/ice_player"
ITEM.Color = Color(255, 255, 255, 77)
ITEM.Weight = 0.1
ITEM.Price = 20	
ITEM.NoBlueprint = true
ITEM.CantDecompile = true
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.ReqCook = { "item_sand", "item_sand", "item_sand", "item_sand", "item_sand" }