ITEM = {}
ITEM.Name = "Charcoal"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Burned wood."
ITEM.Model = "models/props_lab/jar01b.mdl"
ITEM.Color = Color(50, 50, 50)
ITEM.Weight = 0.1
ITEM.LootType = { "Industrial" }
ITEM.Price = 2
ITEM.DontStock = true
ITEM.SellPrice = 1
ITEM.ReqCraft = {"item_wood"}
ITEM.NoBlueprint = true
ITEM.CantDecompile = true
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,4)