ITEM = {}
ITEM.Name = "Wooden Planks"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Planks, created from wood!"
ITEM.Model = "models/dayz/misc/dayz_woodplank2.mdl"
ITEM.Weight = 0.1
ITEM.ViewAngle = Angle(0,90,0)
ITEM.SpawnChance = 40
ITEM.CanIgnite = true
ITEM.DontStock = true
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.ReqCraft = { "item_wood", "item_wood" }
ITEM.NoBlueprint = true
ITEM.CantDecompile = true