ITEM = {}
ITEM.Name = "Gunpowder (Refined)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A mixture of Gunpowder x6"
ITEM.Model = "models/props_lab/jar01a.mdl"
ITEM.Color = Color(255, 0, 0)
ITEM.Weight = 0.6
ITEM.LootType = { "Weapon" }
ITEM.SpawnChance = 25
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.NoBlueprint = true
ITEM.TimeToProcess = 1
ITEM.ReqCraft = { "item_gunpowder_proc", "item_gunpowder_proc" }