ITEM = {}
ITEM.Name = "Diamond Bar"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "I'm rich, bitch!"
ITEM.Model = "models/gml/gold_bar_large.mdl"
ITEM.Material = "models/shiny"
ITEM.Color = Color(0, 178, 255, 255)
ITEM.Weight = 1
ITEM.SellPrice = 5000
ITEM.Category = ""
ITEM.IsCurrency = true
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.NoBlueprint = true
ITEM.CantDecompile = true
ITEM.ReqCraft = { "item_diamondore", "item_diamondore", "item_diamondore" }
ITEM.Rarity = 1
ITEM.LevelReq = 25