ITEM = {}
ITEM.Name = "Bullet Casing (Buckshot)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Bullet casings... what else?"
ITEM.Model = "models/weapons/Shotgun_shell.mdl"
ITEM.Weight = 0
ITEM.Price = 10	
ITEM.SellPrice = 12	
ITEM.SpawnChance = -1
ITEM.CantDecompile = true
ITEM.NoBlueprint = true
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.GivePer = 2
ITEM.TimeToProcess = 3
ITEM.ReqCraft = {"item_metal"}
ITEM.UsedInCrafting = true