ITEM = {}
ITEM.Name = "Gold Ore"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Freshly mined Gold Ore!"
ITEM.Model = "models/dayz/misc/dayz_mineralrock.mdl"
ITEM.Skin = 2
ITEM.Weight = 0.1
ITEM.Price = 300
ITEM.SpawnChance = -1
ITEM.CantCraft = true
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.UsedInCrafting = true
ITEM.Rarity = 1