ITEM = {}
ITEM.Name = "Bowie Knife"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A knife used primarily in trenches."
ITEM.Model = "models/bowie_knife.mdl"
ITEM.Weight = 10
ITEM.LootType = { "Weapon" }
ITEM.SpawnChance = -1
ITEM.Melee = true
ITEM.SpawnOffset = Vector(0,0,0)
ITEM.Weapon = "weapon_bowie"
ITEM.ReqCraft = {"item_ironbar", "item_ironbar", "item_fabric"}
ITEM.Rarity = 3