ITEM = {}
ITEM.Name = "Wrench"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A wrench used to hit things."
ITEM.Model = "models/weapons/w_dangerzone_spanner.mdl"
ITEM.Weight = 10
ITEM.LootType = { "Weapon" }
ITEM.Price = 110
ITEM.SpawnChance = 25
ITEM.Melee = true
ITEM.SpawnOffset = Vector(0,0,0)
ITEM.Weapon = "dangerzone_spanner"
ITEM.ReqCraft = { "item_ironbar", "item_ironbar" }
ITEM.Rarity = 1