ITEM = {}
ITEM.Name = "Axe (Copper)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Chop chop!"
ITEM.Model = "models/weapons/w_gms_hatchet.mdl"
ITEM.Skin = 1
ITEM.Color = Color(255,255,255)
ITEM.Weight = 5
ITEM.LootType = { "Industrial" }
ITEM.SpawnChance = 5
ITEM.Weapon = "weapon_hatchet_copper"
ITEM.Tertiary = true
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.ReqCraft = { "item_copperbar", "item_copperbar", "item_axe" }
ITEM.Rarity = 1