ITEM = {}
ITEM.Name = "Cactus"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Because everyone needs a little prick in their lives."
ITEM.Model = "models/props_lab/cactus.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Basic" }
ITEM.Price = 15
ITEM.SpawnChance = 55
ITEM.CantCraft = true
ITEM.SpawnOffset = Vector(0,0,5)
ITEM.ReqCraft = { "item_plantfibre", "item_plantfibre" }