ITEM = {}
ITEM.Name = "Fuse"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Short, like a certain Scottish man's temper."
ITEM.Model = "models/gibs/furniture_gibs/furniture_chair01a_gib02.mdl"
ITEM.Weight = 0.3
ITEM.Price = 30
ITEM.SpawnChance = -1
ITEM.ReqCraft = { "item_plantfibre", "item_plantfibre", "item_plantfibre", "item_plantfibre", "item_plantfibre" }
ITEM.SpawnOffset = Vector(0,0,4)
ITEM.Rarity = 1