ITEM = {}
ITEM.Name = "AR15"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_rif_m4a1.mdl"
ITEM.Weight = 40
ITEM.Price = 1400
ITEM.Credits = 140
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.LevelReq = 1
ITEM.Primary = true
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_a", "item_part_d", "item_part_g" }
ITEM.Weapon = "cw_ar15"