ITEM = {}

ITEM.Name = "SKS-D"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_rif_ak47.mdl"
ITEM.Weight = 40
ITEM.Price = 2400
ITEM.Credits = 240
ITEM.SpawnChance = 5 -- Out of 100ITEM.
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Primary = true
ITEM.LevelReq = 8
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_a", "item_part_c", "item_part_e" }
ITEM.Weapon = "khr_sks"