ITEM = {}
ITEM.Name = "G3A3"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_snip_g3sg1.mdl"
ITEM.Weight = 40
ITEM.Price = 1800
ITEM.Credits = 180
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Primary = true
ITEM.LevelReq = 8
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_a", "item_part_e", "item_part_g" }
ITEM.Weapon = "cw_g3a3"