ITEM = {}
ITEM.Name = "Barrett M98B"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/cw2/weapons/w_barret_m98_bravo.mdl"
ITEM.Weight = 50
ITEM.Price = 2400
ITEM.Credits = 240
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.CantCraft = true
ITEM.LevelReq = 20
ITEM.Primary = true
ITEM.ReqCraft = { "item_part_a", "item_part_c", "item_part_e", "item_part_f", "item_part_h" }
ITEM.Weapon = "khr_m98b"