ITEM = {}
ITEM.Name = "AK-74"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_rif_ak47.mdl"
ITEM.Weight = 40
ITEM.Price = 1400
ITEM.Credits = 140
ITEM.SpawnChance = 3
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Primary = true
ITEM.LevelReq = 8
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_a", "item_part_d", "item_part_c" }
ITEM.Weapon = "cw_ak74"
ITEM.Rarity = 4