ITEM = {}
ITEM.Name = "M249"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "For the big boys."
ITEM.Model = "models/weapons/cw2_0_mach_para.mdl"
ITEM.Weight = 50
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Primary = true
ITEM.ReqCraft = { "item_part_a", "item_part_d", "item_part_h", "item_part_d", "item_part_g", "item_part_g" }
ITEM.Weapon = "cw_m249_official"
ITEM.LevelReq = 100