ITEM = {}
ITEM.Name = "HK MP5"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_smg_mp5.mdl"
ITEM.Weight = 40
ITEM.Price = 1400
ITEM.Credits = 140
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Primary = true
ITEM.LevelReq = 8
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_a", "item_part_b", "item_part_d" }
ITEM.Weapon = "cw_mp5"