ITEM = {}
ITEM.Name = "Large Backpack"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Large Backpack."
ITEM.Model = "models/fallout 3/backpack_3.mdl"
ITEM.Weight = 25
ITEM.Price = 2500
ITEM.WeightFor = 55
ITEM.BackPack = 55
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, 55) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, -55) end
ITEM.SpawnChance = 1
ITEM.LootType = { "Weapon" }
ITEM.ReqCraft = { "item_fabric", "item_fabric", "item_fabric", "item_plastic", "bp_medium" }
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.Rarity = 1
ITEM.LevelReq = 7