ITEM = {}
ITEM.Name = "Largest Backpack"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Large Backpack with extra pockets."
ITEM.Model = "models/fallout 3/backpack_6.mdl"
ITEM.Weight = 25
ITEM.Price = 4000
ITEM.WeightFor = 100
ITEM.BackPack = 100
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, 100) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, -100) end
ITEM.SpawnChance = 1
ITEM.LootType = { "Weapon" }
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.Rarity = 1	
ITEM.ReqCraft = { "item_fabric", "item_fabric", "item_fabric", "item_plastic", "bp_large2" }
ITEM.LevelReq = 50