ITEM = {}
ITEM.Name = "Small Backpack"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Small Backpack."
ITEM.Model = "models/fallout 3/backpack_1.mdl"
ITEM.Weight = 10
ITEM.Price = 500
ITEM.WeightFor = 25
ITEM.BackPack = 25
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, 25) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, -25) end
ITEM.SpawnChance = 1
ITEM.NoBlueprint = true
ITEM.LootType = { "Weapon" }
ITEM.ReqCraft = { "item_fabric", "item_fabric", "item_fabric", "item_part_a", "item_plank" }
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.Rarity = 1
ITEM.LevelReq = 3