ITEM = {}
ITEM.Name = "Santa Hat"
ITEM.Angle = Angle(-180,-90,-90)
ITEM.Desc = "Made out of Milk Chocolate & Protects the wearer's brains!"
ITEM.Model = "models/cloud/kn_santahat.mdl"
ITEM.Weight = 1
ITEM.Hat = true
ITEM.LootType = { "Hat" }
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,5)
ITEM.EatFor = 15
ITEM.DrinkFor = 15
ITEM.Rarity = 1
ITEM.SellPrice = 200
ITEM.ReqCraft = { "item_milkchocolate", "item_ironbar", "item_milkchocolate"}
ITEM.CantDecompile = true
ITEM.NoBlueprint = true
ITEM.CantCraft = true
ITEM.EatFunction = function(ply, item) ply:DoProcess(item, "Eating", 3, "eat.wav", 0, "npc/barnacle/barnacle_gulp2.wav") end
ITEM.ProcessFunction = function(ply, item) ply:EatDrink(item, 15, 15) end