ITEM = {}
ITEM.Name = "Hazmat Suit"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Prevents Radiation but degrades over time"
ITEM.Model = "models/props_c17/SuitCase001a.mdl"
ITEM.Weight = 1
ITEM.Skin = 0
ITEM.ReqCraft = { "item_plastic", "item_plastic", "item_ironbar", "item_fabric", "item_fabric" }
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,10)
ITEM.Body = true
ITEM.RadsFor = -100
ITEM.IsHazmat = true
ITEM.BodyModel = "models/DxN/cod_ghosts/hazmat_pm.mdl"
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.LootType = { "Industrial", "Weapon" }
ITEM.Rarity = 1
ITEM.LevelReq = 14