ITEM = {}
ITEM.Name = "Ghillie"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Standard Edition Camouflage suit"
ITEM.Model = "models/props_c17/SuitCase001a.mdl"
ITEM.Weight = 1
ITEM.ReqCraft = { "item_fabric", "item_fabric" }
ITEM.SpawnChance = 25
ITEM.SpawnOffset = Vector(0,0,10)
ITEM.Body = true
ITEM.WeightFor = 10
ITEM.BodyModel = "models/combine_sniper.mdl"
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, 10) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity, -10) end
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.LootType = { "Industrial", "Weapon" }
ITEM.Rarity = 1
ITEM.LevelReq = 10