ITEM = {}
ITEM.Name = "Bucket"
ITEM.Angle = Angle(-180,-90,-90)
ITEM.Desc = "Junk."
ITEM.Model = "models/props_junk/MetalBucket01a.mdl"
ITEM.Weight = 1
ITEM.Hat = true
ITEM.LootType = { "Hat" }
ITEM.SpawnChance = 20
ITEM.SpawnOffset = Vector(0,0,5)
ITEM.Rarity = 1
ITEM.ReqCraft = { "item_metal", "item_metal" }
ITEM.NoBlueprint = true