ITEM = {}
ITEM.Name = "E (Weapon Part)"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "A part for a weapon ??"
ITEM.Model = "models/weapons/w_eq_eholster.mdl"
ITEM.Weight = 5
ITEM.Price = 100
ITEM.SpawnChance = 10
ITEM.SpawnOffset = Vector(0,0,0)
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.LootType = { "Industrial", "Weapon" }
ITEM.ReqCraft = { "item_plastic", "item_copperbar", "item_ironbar", "item_plank" }