ITEM = {}
ITEM.Name = "Combat Pants"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Combat pants with extra leg pockets."
ITEM.Model = "models/props_junk/garbage_bag001a.mdl"
ITEM.Material = "phoenix_storms/metalset_1-2"
ITEM.Weight = 1
ITEM.WeightFor = 15
ITEM.Price = 200
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,10)
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity,  15 ) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity,  -15 ) end
ITEM.Pants = true
ITEM.ReqCraft = {"item_fabric", "item_fabric", "item_ironbar", "item_plastic"}
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.LootType = { "Basic", "Industrial", "Weapon" }
ITEM.Rarity = 1
ITEM.LevelReq = 4