ITEM = {}
ITEM.Name = "Baggy Pants"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = "Stretchy, baggy pants with a few pockets."
ITEM.Model = "models/props_junk/garbage_bag001a.mdl"
ITEM.Material = "models/props_c17/FurnitureMetal001a"
ITEM.Weight = 1
ITEM.WeightFor = 10
ITEM.Price = 200
ITEM.SpawnChance = 2
ITEM.SpawnOffset = Vector(0,0,10)
ITEM.EquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity,  10 ) end
ITEM.DEquipFunc = function(ply, item, class, rarity) ply:AddAdditionalWeight( rarity,  -10 ) end
ITEM.Pants = true
ITEM.NoBlueprint = true
ITEM.ReqCraft = {"item_fabric", "item_fabric"}
ITEM.SpawnAngle = Angle(0,0,0)
ITEM.LootType = { "Basic", "Industrial", "Weapon" }
ITEM.Rarity = 1