ITEM = {}
ITEM.Name = "Copper Armor"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Basic armor."
ITEM.Model = "models/combine_helicopter/bomb_debris_3.mdl"
ITEM.Material = "models/props_pipes/GutterMetal01a"
ITEM.Weight = 5
ITEM.Price = 1000
ITEM.BodyArmor = 60
ITEM.SpawnChance = 1
ITEM.LevelReq = 6
ITEM.NoGiveOnBreak = true
ITEM.ReqCraft = { "item_copperbar", "item_copperbar", "item_armor_stone" }
ITEM.LootType = { "Weapon" }
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.Rarity = 1