ITEM = {}
ITEM.Name = "Egg"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Cooked Egg."
ITEM.Model = "models/griim/foodpack/egg.mdl"
ITEM.Weight = 0.5
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.NoBlueprint = true
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.ReqCook = { "item_egg" }
ITEM.EatFor = 10
ITEM.Rarity = 1