ITEM = {}
ITEM.Name = "Stale Take-away"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Eat this to restore hunger."
ITEM.Model = "models/props_junk/garbage_takeoutcarton001a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 35
ITEM.SpawnChance = 90
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.EatFor = 10