ITEM = {}
ITEM.Name = "Pie (Milk Chocolate)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Milk Chocolate Pie. "
ITEM.Model = "models/theforgottenarchitect/pie.mdl"
ITEM.Skin = 1
ITEM.Color = Color(127, 85, 0)
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 10
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.EatFor = 25
ITEM.ReqCook = { "item_emptypie", "item_milkchocolate", "item_milkchocolate" }
ITEM.Rarity = 1