ITEM = {}
ITEM.Name = "Pie (Apple)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "An Apple Pie. "
ITEM.Model = "models/theforgottenarchitect/pie.mdl"
ITEM.Skin = 1
ITEM.Color = Color(130, 0, 0)
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.EatFor = 35
ITEM.ReqCook = { "item_emptypie", "item_apple", "item_apple" }
ITEM.Rarity = 1