ITEM = {}
ITEM.Name = "Pie (Cheese)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Cheese Pie. "
ITEM.Model = "models/theforgottenarchitect/pie.mdl"
ITEM.Skin = 1
ITEM.Color = Color(255, 255, 0)
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.ReqCook = { "item_emptypie", "item_cheese", "item_cheese" }
ITEM.EatFor = 35
ITEM.Rarity = 1