ITEM = {}
ITEM.Name = "Pancake"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = ""
ITEM.Model = "models/griim/foodpack/pancakesingle.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 10
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.ReqCook = { "item_drink3", "item_egg" }
ITEM.EatFor = 10
ITEM.Rarity = 1