ITEM = {}
ITEM.Name = "Melon"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Eat this to restore a little hunger/thirst."
ITEM.Model = "models/props_junk/watermelon01.mdl"
ITEM.Weight = 1
ITEM.Price = 30
ITEM.LootType = { "Food" }
ITEM.SpawnChance = 55
ITEM.Modelscale = 0.6
ITEM.SpawnOffset = Vector(0,0,7)
ITEM.EatFor = 10
ITEM.DrinkFor = 10
ITEM.ReqCraft = { "item_plantfibre", "item_plantfibre" }
ITEM.CantCraft = true