ITEM = {}
ITEM.Name = "Banana"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Variety of applications."
ITEM.Model = "models/tsbb/fruits/banana.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 30
ITEM.SpawnChance = 55
ITEM.SpawnOffset = Vector(0,0,3)
ITEM.EatFor = 10
ITEM.ReqCraft = { "item_plantfibre","item_plantfibre" }
ITEM.CantCraft = true