ITEM = {}
ITEM.Name = "Pie (Orange)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "An Orange Pie. "
ITEM.Model = "models/theforgottenarchitect/pie.mdl"
ITEM.Skin = 1
ITEM.Color = Color(182, 88, 0)
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.EatFor = 30
ITEM.ReqCook = { "item_emptypie", "item_food4", "item_food4" }
ITEM.Rarity = 1