ITEM = {}
ITEM.Name = "Cheesy Pizza"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "O.M.G."
ITEM.Model = "models/griim/foodpack/cheesepizza.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.ReqCook = { "item_breadslice", "item_breadslice", "item_breadslice", "item_cheese" }
ITEM.EatFor = 20
ITEM.Rarity = 1