ITEM = {}
ITEM.Name = "Pie (Dark Chocolate)"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A Dark Chocolate Pie. "
ITEM.Model = "models/theforgottenarchitect/pie.mdl"
ITEM.Skin = 1
ITEM.Color = Color(77, 58, 7)
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 25
ITEM.SpawnChance = 1
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.TimeToProcess = 5
ITEM.EatFor = 30
ITEM.ReqCook = { "item_emptypie", "item_chocolate", "item_chocolate" }
ITEM.Rarity = 1