ITEM = {}
ITEM.Name = "Beer"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Overindulgence may result in death."
ITEM.Model = "models/props_junk/GlassBottle01a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 75
ITEM.SpawnChance = 60
ITEM.DrinkFor = 10
ITEM.SpawnOffset = Vector(0,0,9)