ITEM = {}
ITEM.Name = "Milk"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "For all your bovine needs"
ITEM.Model = "models/props_junk/garbage_milkcarton002a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 10
ITEM.SpawnChance = 40
ITEM.DrinkFor = 10
ITEM.SpawnOffset = Vector(0,0,8)