ITEM = {}
ITEM.Name = "Irn Bru"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Scotland's other National Drink."
ITEM.Model = "models/props_cans/irnbru01a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 125
ITEM.SpawnChance = 35
ITEM.NoFire = true
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.DrinkFor = 15
ITEM.StaminaFor = 30
ITEM.ReqCook = { "item_emptycan", "item_drink1", "item_gasoline" }
ITEM.Rarity = 1