ITEM = {}
ITEM.Name = "Phoenix Phuze"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "The label reads: 'Caffeine free'..."
ITEM.Model = "models/dayz/drinks/dayz_phoenixphuze.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 125
ITEM.SpawnChance = 25
ITEM.SpawnOffset = Vector(0,0,6)
ITEM.DrinkFor = 15
ITEM.Rarity = 1