ITEM = {}
ITEM.Name = "Soda Can"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Fizzy pop from god knows when."
ITEM.Model = "models/props_junk/PopCan01a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 101
ITEM.SpawnChance = 90
ITEM.DrinkFor = 10
ITEM.GiveItemOnProcess = "item_emptycan"
ITEM.StaminaFor = 5
ITEM.SpawnOffset = Vector(0,0,3.5)