ITEM = {}
ITEM.Name = "Cup of Coffee"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "A little pick me up in the morning."
ITEM.Model = "models/props_junk/garbage_coffeemug001a.mdl"
ITEM.Weight = 1
ITEM.LootType = { "Food" }
ITEM.Price = 45
ITEM.SpawnChance = 45
ITEM.StaminaFor = 15
ITEM.DrinkFor = 5
ITEM.SpawnOffset = Vector(0,0,3.5)