ITEM = {}
ITEM.Name = "Fancy Farmer"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Quicker Plant Growth (3rd less) and Better Plant Yield (min 2)"
ITEM.Model = "models/props_junk/terracotta01.mdl"
ITEM.Color = Color(255, 210, 0)
ITEM.Material = "models/shiny"
ITEM.Weight = 0
ITEM.Credits = 500
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.NoConsumeFromFloor = true
ITEM.ProcessFunction = function(ply, item, class) ply:GivePerk(class) end