ITEM = {}
ITEM.Name = "Hoarder"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Bullet Casings and Items from Kills are automatically collected - Does not work if you are overweight"
ITEM.Model = "models/weapons/w_defuser.mdl"
ITEM.Color = Color(255, 210, 0)
ITEM.Material = "models/shiny"
ITEM.Weight = 0
ITEM.Credits = 500
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.NoConsumeFromFloor = true
ITEM.ProcessFunction = function(ply, item, class) ply:GivePerk(class) end