ITEM = {}
ITEM.Name = "Strong Back"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Unlocks the ability to carry 200% the normal weight amount"
ITEM.Model = "models/props_c17/tv_monitor01.mdl"
ITEM.Color = Color(255, 210, 0)
ITEM.Material = "models/shiny"
ITEM.Weight = 0
ITEM.Credits = 1500
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.NoConsumeFromFloor = true
ITEM.ProcessFunction = function(ply, item, class) ply:GivePerk(class) end