ITEM = {}
ITEM.Name = "Enlightenment"
ITEM.Angle = Angle(0,0,0)
ITEM.Desc = "Negates the need for a flashlight - Press F to pay respects"
ITEM.Model = "models/raviool/flashlight.mdl"
ITEM.Color = Color(255, 210, 0)
ITEM.Material = "models/shiny"
ITEM.Weight = 0
ITEM.Credits = 250
ITEM.SpawnChance = -1
ITEM.SpawnOffset = Vector(0,0,3.5)
ITEM.NoConsumeFromFloor = true
ITEM.ProcessFunction = function(ply, item, class) ply:GivePerk(class) end