ITEM = {}
ITEM.Name = "M1911"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/cw_pist_m1911.mdl"
ITEM.Weight = 30
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.AmmoOverride = "9x18MM"
ITEM.Secondary = true
ITEM.LevelReq = 6
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_g", "item_part_d", "item_ironbar" }
ITEM.Weapon = "cw_m1911"
ITEM.Rarity = 3