ITEM = {}
ITEM.Name = "FN Five-SeveN"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_pist_fiveseven.mdl"
ITEM.Weight = 30
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Secondary = true
ITEM.LevelReq = 7
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_g", "item_part_d" }
ITEM.Weapon = "cw_fiveseven"
ITEM.Rarity = 3