ITEM = {}
ITEM.Name = "P99"
ITEM.Angle = Angle(90,90,90)
ITEM.Desc = ""
ITEM.Model = "models/weapons/w_pist_p228.mdl"
ITEM.Weight = 30
ITEM.SpawnChance = 5
ITEM.SpawnOffset = Vector(0,0,1)
ITEM.SpawnAngle = Angle(0,0,90)
ITEM.LootType = { "Weapon" }
ITEM.Gun = true
ITEM.Secondary = true
ITEM.LevelReq = 0
ITEM.Craftable = true
ITEM.ReqCraft = { "item_part_b", "item_part_a", "item_ironbar" }
ITEM.Weapon = "cw_p99"
ITEM.NoBlueprint = true
ITEM.Rarity = 3